import React from "react";
import type { Metadata } from "next";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { FloatingWhatsApp } from "@/components/layout/FloatingWhatsApp";
import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { SITE_CONFIG } from "@/data/siteConfig";

export const metadata: Metadata = {
  title: "Terms & Conditions — Gaurav Marbles",
  description:
    "Showroom inquiry terms, quotation policies, and natural stone characteristics disclosure for Gaurav Marbles Firozabad.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen flex flex-col bg-[#FDFCF7]">
      <Navbar />

      <div className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 font-sans-clean">
        <Breadcrumbs
          items={[
            { name: "Legal", url: "/terms" },
            { name: "Terms & Conditions", url: "/terms" },
          ]}
        />

        <div className="mt-6 mb-10">
          <h1 className="font-serif-luxury text-3xl sm:text-4xl font-bold text-stone-900">
            Terms & Conditions
          </h1>
          <p className="text-xs text-stone-500 mt-2">
            Last Updated: {new Date().toLocaleDateString("en-IN", { month: "long", year: "numeric" })}
          </p>
        </div>

        <div className="bg-white border border-stone-200 rounded-xs p-6 sm:p-10 shadow-xs space-y-6 text-xs sm:text-sm text-stone-700 leading-relaxed">
          <section className="space-y-2">
            <h2 className="font-serif-luxury text-base font-bold text-stone-900">
              1. Showroom Business Website Nature
            </h2>
            <p>
              This website serves as a digital showroom for <strong>{SITE_CONFIG.name}</strong>. Products shown on this website represent available collections, typical dimensions, and quarry selections. Product listings and online inquiries do not constitute a binding sales contract until confirmed by written estimate, physical inspection, and agreement at our showroom.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="font-serif-luxury text-base font-bold text-stone-900">
              2. Natural Stone Characteristics & Inherent Variations
            </h2>
            <div className="p-4 bg-amber-50/70 border border-amber-200/80 rounded-xs text-amber-950 space-y-2">
              <strong className="block font-semibold">Important Stone Disclosure:</strong>
              <p className="text-xs leading-relaxed">
                Marble and granite are natural geological formations quarried from the earth. Natural variations in color tone, veining patterns, crystalline structures, pits, fissures, and mineral inclusions are inherent characteristics of authentic stone and are not considered manufacturing defects.
              </p>
              <p className="text-xs leading-relaxed">
                We strongly advise all customers to inspect the actual slab lot in person at our Firozabad showroom before finalizing cutting or dispatch.
              </p>
            </div>
          </section>

          <section className="space-y-2">
            <h2 className="font-serif-luxury text-base font-bold text-stone-900">
              3. Quotations & Pricing Validity
            </h2>
            <p>
              Quotations provided through our website, phone, or WhatsApp are based on prevailing market rates, quarry supply, and lot availability at the time of inquiry. Prices may vary based on slab thickness, surface processing, edge moulding, and transportation requirements.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="font-serif-luxury text-base font-bold text-stone-900">
              4. Area Calculator Estimates
            </h2>
            <p>
              Calculations generated by the website&apos;s Marble & Tile Area Calculator are approximate guidance only. Final material requirements must always be verified on site by the client&apos;s contractor, architect, or tile mason before placing a final order.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="font-serif-luxury text-base font-bold text-stone-900">
              5. Governing Jurisdiction
            </h2>
            <p>
              Any disputes or legal matters arising in connection with orders placed with Gaurav Marbles shall be subject to the exclusive jurisdiction of the competent courts in <strong>Firozabad, Uttar Pradesh, India</strong>.
            </p>
          </section>
        </div>
      </div>

      <Footer />
      <FloatingWhatsApp />
    </main>
  );
}
